### ISSUE TITLE
Some problems with render "Masked" textures

### ISSUE THREAD

**Issue by DeMNiX** [mikkokko/csldr#29]
Hello
we have some problems with render models that use textures with alpha channels and $texrendermode masked on models.
all parts of models that used this flag is "invisible"

https://youtu.be/xYY7sWroifM

**Comment by DeMNiX** [comment]
[zm_buffclass23s1tr_eg.zip](https://github.com/mikkokko/csldr/files/12803075/zm_buffclass23s1tr_eg.zip)
u can use this one for tests

**Comment by mikkokko** [comment]
Looks like the same issue as in #16. The model looks fine on my machine. What GPU do you have?

**Comment by DeMNiX** [comment]
Laptop gtx1050ti

**Comment by mikkokko** [comment]
I compiled a debug dll for you to try since I can't reproduce the issue myself: [client.zip](https://github.com/mikkokko/csldr/files/12836992/client.zip).

I added some checks for GL_ALPHA_TEST, it should spam the console if it's enabled for whatever reason. I also made the fragment shader show all opaque fragments as blue and transparent ones as red. If the issue is caused by the fragment shader discarding all fragments, the masked parts of the models you're having issues with should be fully red.

**Comment by DeMNiX** [comment]
The results: https://youtu.be/HYHhyx8j7qA

**Comment by DeMNiX** [comment]
> Looks like the same issue as in #16. The model looks fine on my machine. What GPU do you have?

can u give this compiled DLL, maybe problem was with it?

**Comment by mikkokko** [comment]
Aw yeah, I thought I published a release that included the fix but I never did. This should work then [client.zip](https://github.com/mikkokko/csldr/files/12837256/client.zip).
