### ISSUE TITLE
Source like addon system

### ISSUE THREAD

**Issue by hampta** [mikkokko/csldr#41]
I would like a system with separate folders for each addon. the `cstrike_addon` folder looks like a trash can.

**Comment by H3ADROOM** [comment]
I agree, this shit just hurts to look at, too messy

**Comment by mikkokko** [comment]
Adding this to the client.dll would be technically possible but not very robust since the game loads files before client.dll gets loaded. A better way to achieve this would be with a filesystem_stdio replacement. I worked on one that used PhysicsFS a while back. I'll let you know if I ever get it released.
